name: AppImage Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter channel dev
    - run: flutter upgrade
    - run: flutter config --enable-linux-desktop
    - name: "Install dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential pkg-config
    - run: cd hello_flutter && flutter build linux
    - name: pack
      uses: docker://appimagecrafters/appimage-builder:0.8.5
      with:
        entrypoint: appimage-builder
        args: --recipe ./AppImageBuilder.yml --skip-test
    - uses: actions/upload-artifact@v2
      with:
        name: AppImage
        path: './*.AppImage*'
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Continuous build
        automatic_release_tag: 'continuous'
        prerelease: true
        draft: false
        files: './*.AppImage*'
        repo_token: ${{ secrets.GITHUB_TOKEN }}